services:
  mongodb:
    image: mongo:latest
    command: ["mongod", "--bind_ip_all"]  # Allow connections from other containers
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=0000
      - MONGO_INITDB_DATABASE=defensym
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5148:8080"  # Map to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080  # Explicitly set URLs
      - ConnectionStrings__DbConnection=mongodb://root:0000@mongodb:27017/defensym?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
    driver: local